# Generated by Django 3.2.5 on 2021-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_images_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Link'),
        ),
    ]
