# Generated by Django 3.2.5 on 2021-07-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Link'),
        ),
    ]
